apiVersion:  apps/v1
kind:  DaemonSet
metadata:
    name: nginx-ds
    labels:
      env: demo
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
      - image: nginx:latest
        name: nginx-pod 
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      env: demo   
 