apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: demo
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd   
    

