apiVersion:  v1
kind:  ReplicationController
metadata:
    name: nginx-rc
    labels:
      env: demo
spec:
  template:
    metadata:
     labels:
      run: nginx-pod
     name: nginx-pod
    spec:
     containers:
     - image: nginx:latest
       name: nginx-pod
  replicas:  2     
 