apiVersion:  apps/v1
kind:  ReplicaSet
metadata:
    name: nginx-rs
    labels:
      env: demo
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
      - image: nginx:latest
        name: nginx-pod
  replicas:  2  
  selector:
    matchLabels:
      env: demo   
 